### ISSUE TITLE
Pagina de Inicio sobre la billetera virtual "8"

### ISSUE THREAD

**Issue by DarioR88** [fyalva/SAPUCAI#17]
COMO nuevo Usuario QUIERO saber todo sobre la billetera virtual PARA saber sus ventajas y beneficios - "8"

**Comment by DarioR88** [comment]
Iniciando el maquetado de la pagina de Sapucai

**Comment by ricardorivaspereda** [comment]
@DarioR88  agrega boton de login , no olvidar el head correspondiente

**Comment by roquegimenez** [comment]
tener logo

**Comment by roquegimenez** [comment]
NavBar , pie de pagina que no se como se escribe.
ademas encontener una presentacion sobre la billetera

**Comment by roquegimenez** [comment]
NavBar deber contener:
logo, Sobre Nosotros, Funciones, Promociones,Ayuda y un boton de login

**Comment by roquegimenez** [comment]
cuerpo de pagina, contener una presentacion vendiendo nuestro producto
con alguna imagen referida a la app

**Comment by roquegimenez** [comment]
pie de pagina -
informacion sobre direccion fiscal
terminos de uso
politicas de privacidad
centro de ayuda
sobre la aplicacion
